# Generated by Django 3.2.10 on 2021-12-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('contract_id', models.IntegerField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=150)),
                ('clients_client_id', models.IntegerField(blank=True, null=True)),
                ('suppliers_supplier_id', models.IntegerField(blank=True, null=True)),
                ('valuables_data_barcode', models.IntegerField(blank=True, null=True)),
                ('product_amount', models.IntegerField()),
                ('expected_completion_date', models.DateField()),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('op_journal_operation_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('worker_worker_id', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=150)),
                ('pending_delivery_date', models.DateField()),
            ],
            options={
                'db_table': 'deliveries',
            },
        ),
        migrations.CreateModel(
            name='Finances',
            fields=[
                ('finance_op_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment', models.IntegerField()),
                ('contracts_contract_id', models.IntegerField(unique=True)),
                ('transaction_completion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'finances',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('payment', models.IntegerField()),
                ('planned_work_time', models.IntegerField()),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='OperationsJournal',
            fields=[
                ('operation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=150)),
                ('contracts_contract_id', models.IntegerField(unique=True)),
                ('valuables_data_barcode', models.IntegerField(blank=True, null=True)),
                ('clients_client_id', models.IntegerField(blank=True, null=True)),
                ('worker_worker_id', models.IntegerField(blank=True, null=True)),
                ('operation_date', models.DateField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'operations_journal',
            },
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('barcode', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.IntegerField()),
                ('zone_type', models.CharField(max_length=150)),
                ('zone_number', models.IntegerField()),
            ],
            options={
                'db_table': 'registry',
            },
        ),
        migrations.CreateModel(
            name='Relation16',
            fields=[
                ('worker_worker_id', models.IntegerField(primary_key=True, serialize=False)),
                ('registry_barcode', models.IntegerField()),
            ],
            options={
                'db_table': 'relation_16',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='ValuablesData',
            fields=[
                ('barcode', models.IntegerField(primary_key=True, serialize=False)),
                ('package_type', models.CharField(max_length=150)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('appropriate_zones', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'valuables_data',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('jobs_job_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('passport_number', models.IntegerField()),
                ('phone_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'worker',
            },
        ),
    ]
