# Generated by Django 3.2.10 on 2021-12-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_clients_contracts_deliveries_finances_jobs_operationsjournal_registry_relation16_suppliers_valuables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
