# Generated by Django 3.2.10 on 2021-12-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_clients_client_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clients',
            table=None,
        ),
    ]
