# Generated by Django 3.2.10 on 2021-12-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_clients_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clients',
            table='clients',
        ),
    ]
