# Generated by Django 3.2.10 on 2021-12-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_clients_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contracts',
            name='clients_client_id',
            field=models.IntegerField(blank=True, default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contracts',
            name='suppliers_supplier_id',
            field=models.IntegerField(blank=True, default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contracts',
            name='valuables_data_barcode',
            field=models.IntegerField(blank=True, default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='op_journal_operation_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='worker_worker_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='finances',
            name='contracts_contract_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='operationsjournal',
            name='clients_client_id',
            field=models.IntegerField(blank=True, default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operationsjournal',
            name='valuables_data_barcode',
            field=models.IntegerField(blank=True, default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operationsjournal',
            name='worker_worker_id',
            field=models.IntegerField(blank=True, default='None'),
            preserve_default=False,
        ),
    ]
